name: Share data between jobs

on: workflow_dispatch

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: actions_runner_dev
    steps:
      - name: suma
      run: |
          expr 3 + 7 > math-homework.txt
  


 